"""Initial commit

Revision ID: 53a6126c9473
Revises: 
Create Date: 2024-09-30 20:30:43.732497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a6126c9473'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('end_date'),
    sa.UniqueConstraint('start_date')
    )
    op.create_index(op.f('ix_availabilities_doctor_id'), 'availabilities', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_availabilities_id'), 'availabilities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_availabilities_id'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_doctor_id'), table_name='availabilities')
    op.drop_table('availabilities')
    # ### end Alembic commands ###
